# 1. Importing Packages

In [2]:
# On the instance where you are running jupyter,
# authenticate with gcloud first:
#
#     gcloud auth application-default login

import bigframes.pandas as bpd

bpd.options.bigquery.location = "US"

import pandas as pd
from langchain.agents import AgentExecutor, OpenAIFunctionsAgent
# from langchain.chat_models import ChatOpenAI
# from langchain.embeddings import OpenAIEmbeddings
# from langchain.prompts import ChatPromptTemplate, MessagesPlaceholder
# from langchain.pydantic_v1 import BaseModel, Field
# from langchain.tools.retriever import create_retriever_tool
# from langchain.vectorstores import FAISS
# from langchain_experimental.tools import PythonAstREPLTool
import bigframes.pandas as bpd
from langchain.agents.agent_types import AgentType
from langchain_experimental.agents.agent_toolkits import create_pandas_dataframe_agent
from langchain_openai import ChatOpenAI
from langchain_openai import OpenAI
from langchain.embeddings import OpenAIEmbeddings


from langchain.text_splitter import CharacterTextSplitter
from langchain_community.document_loaders import DataFrameLoader
from langchain.vectorstores import Chroma
from langchain_community.vectorstores import FAISS


from langchain.prompts import ChatPromptTemplate, MessagesPlaceholder

In [3]:
big_frames_df = bpd.read_gbq("annular-form-389809.merged_data.crm_ga4")

In [4]:
df = big_frames_df.to_pandas()

In [6]:
df.head()

,name,job,created,transactions,revenue,permission,crm_id,cid,event_date,event_timestamp,...,user_ltv,device,geo,app_info,traffic_source,stream_id,platform,event_dimensions,ecommerce,items
0,Anjali Brekke,Patent attorney,2017-03-21 20:27:35,50,5949.09,TRUE,CRM090719,76876267.6458108853,20210131,1612078488071307,...,"{'revenue': 0.0, 'currency': 'USD'}","{'category': 'desktop', 'mobile_brand_name': '...","{'continent': 'Americas', 'sub_continent': 'No...",<NA>,"{'medium': 'cpc', 'name': '<Other>', 'source':...",2100450278,WEB,<NA>,"{'total_item_quantity': None, 'purchase_revenu...",[]
1,Micayla Mertz PhD,Mental health nurse,2015-04-23 15:56:54,33,1471.69,FALSE,CRM129988,59954005.8371620997,20210131,1612122752738156,...,"{'revenue': 0.0, 'currency': 'USD'}","{'category': 'desktop', 'mobile_brand_name': '...","{'continent': 'Americas', 'sub_continent': 'No...",<NA>,"{'medium': 'organic', 'name': '(organic)', 'so...",2100450278,WEB,<NA>,"{'total_item_quantity': None, 'purchase_revenu...",[]
2,Dr. Carlie Stoltenberg PhD,Environmental consultant,2013-10-16 08:41:59,43,4671.13,TRUE,CRM046684,67907322.3529417392,20210131,1612080532715207,...,"{'revenue': 0.0, 'currency': 'USD'}","{'category': 'desktop', 'mobile_brand_name': '...","{'continent': 'Americas', 'sub_continent': 'No...",<NA>,"{'medium': '(none)', 'name': '(direct)', 'sour...",2100450278,WEB,<NA>,"{'total_item_quantity': None, 'purchase_revenu...",[]
3,Karly Hermiston,Clinical research associate,2012-12-22 15:49:42,50,6783.52,TRUE,CRM053029,3887217.5565940242,20210131,1612096798908599,...,"{'revenue': 0.0, 'currency': 'USD'}","{'category': 'mobile', 'mobile_brand_name': 'A...","{'continent': 'Europe', 'sub_continent': 'Sout...",<NA>,"{'medium': 'referral', 'name': '(referral)', '...",2100450278,WEB,<NA>,"{'total_item_quantity': None, 'purchase_revenu...",[]
4,Jerri Swaniawski-Murray,"Scientist, research (maths)",2017-08-31 20:16:14,24,2100.34,TRUE,CRM020043,1995358.8902221335,20210131,1612109923318632,...,"{'revenue': 0.0, 'currency': 'USD'}","{'category': 'desktop', 'mobile_brand_name': '...","{'continent': 'Americas', 'sub_continent': 'No...",<NA>,"{'medium': '(data deleted)', 'name': '(data de...",2100450278,WEB,<NA>,"{'total_item_quantity': None, 'purchase_revenu...",[]

## Querying pandas dataframe

In [5]:
llm = OpenAI(temperature=0, openai_api_key = "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")

In [6]:
embeddings = OpenAIEmbeddings(openai_api_key = "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")

/root/anaconda3/envs/langchain/lib/python3.11/site-packages/langchain_core/_api/deprecation.py:117: LangChainDeprecationWarning: The class `langchain_community.embeddings.openai.OpenAIEmbeddings` was deprecated in langchain-community 0.1.0 and will be removed in 0.2.0. An updated version of the class exists in the langchain-openai package and should be used instead. To use it run `pip install -U langchain-openai` and import as `from langchain_openai import OpenAIEmbeddings`.
  warn_deprecated(

### Defining pandas dataframe loader

In [7]:
loader = DataFrameLoader(df, page_content_column="name")

loader.load()

text_splitter = CharacterTextSplitter(
    separator = "\n",
    chunk_size = 200,
    chunk_overlap = 0
)


docs = loader.load_and_split(
    text_splitter = text_splitter
)

### Defining Vectorstore Instance

In [8]:
db = FAISS.from_documents(docs, embeddings)

In [10]:
# creates chroma instance and calculates embeddings for all docs
db = FAISS.from_documents(
    docs, 
    embedding = embeddings,
    persist_directory = "df_emb" # persists embeddings in SQLite directory on computer
)

TypeError: FAISS.__init__() got an unexpected keyword argument 'persist_directory'

In [9]:
query = "Which name has the highest transaction amount? Please show the transaction amount."
docs = db.similarity_search(query)
print(docs[0].page_content)

Doshia Hilll

# Original CRM Features
- Skip to next section for ingest of larger BQ data and enriched features

In [9]:
# Load data
df = bpd.read_gbq("SELECT name, job, created, transactions, revenue, permission, crm_id, FROM `annular-form-389809.merged_data.crm_ga4`LIMIT 50").to_pandas()

In [52]:
# Defining agent
agent = create_pandas_dataframe_agent(OpenAI(temperature=0, openai_api_key = "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"), df, verbose=True)

In [20]:
df.head()

,name,job,created,transactions,revenue,permission,crm_id
0,Mr. Austen Conn,Applications developer,2002-11-15 23:03:50,621,79718.09,TRUE,CRM000826
1,Mr. Austen Conn,Applications developer,2002-11-15 23:03:50,621,79718.09,TRUE,CRM000826
2,Mr. Austen Conn,Applications developer,2002-11-15 23:03:50,621,79718.09,TRUE,CRM000826
3,Mr. Austen Conn,Applications developer,2002-11-15 23:03:50,621,79718.09,TRUE,CRM000826
4,Mr. Austen Conn,Applications developer,2002-11-15 23:03:50,621,79718.09,TRUE,CRM000826

In [29]:
df = df.astype({'revenue':'float'})

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   name          50 non-null     string
 1   job           50 non-null     string
 2   created       50 non-null     string
 3   transactions  50 non-null     string
 4   revenue       50 non-null     float64
 5   permission    50 non-null     string
 6   crm_id        50 non-null     string
dtypes: float64(1), string(6)
memory usage: 5.6 KB

### Testing Basic Prompts

Learnings
- You have assign correct dtype to each column

In [53]:
# Defining prompts

row_count = "How many rows are there?"

distinct_users = "How many distinct users are there? What are their names?"

value_per_distinct_user = "How many distinct users are there? How much value has each brought?"

In [54]:
agent.run(value_per_distinct_user)

> Entering new AgentExecutor chain...
Thought: I need to find the number of unique users and their total revenue.
Action: python_repl_ast
Action Input: df['name'].nunique()1010 unique users
Action: python_repl_ast
Action Input: df.groupby('name')['revenue'].sum()name
Demario Wiza                29091.06
Dr. Eulalie Beer PhD        68934.70
Hillary Powlowski          166873.92
Ima Bahringer               16911.30
Kenia Moen                  73128.39
Lesta Effertz                6996.70
Mr. Austen Conn            398590.45
Mr. Delmar Nitzsche          4802.40
Perri Adams                141831.65
Rogers Cummerata-Lehner      3871.64
Name: revenue, dtype: float6410 unique users with their respective total revenue
Final Answer: There are 10 distinct users and their total revenue is shown above.

> Finished chain.

'There are 10 distinct users and their total revenue is shown above.'

### Pasing template to agent

In [34]:
TEMPLATE = """You are working with a pandas dataframe in Python. The name of the dataframe is `df`.
It is important to understand the attributes of the dataframe before working with it. This is the result of running `df.head().to_markdown()`

<df>
{dhead}
</df>

You are not meant to use only these rows to answer questions - they are meant as a way of telling you about the shape and schema of the dataframe.
You also do not have use only the information here to answer questions - you can run intermediate queries to do exporatory data analysis to give you more information as needed.

You have a tool called `person_name_search` through which you can lookup a person by name and find the records corresponding to people with similar name as the query.
You should only really use this if your search term contains a persons name. Otherwise, try to solve it with code.

For example:

<question>How old is Jane?</question>
<logic>Use `person_name_search` since you can use the query `Jane`</logic>

<question>Who has id 320</question>
<logic>Use `python_repl` since even though the question is about a person, you don't know their name so you can't include it.</logic>
"""

In [39]:
template = TEMPLATE.format(dhead=df.head().to_markdown())

In [59]:
prompt = ChatPromptTemplate.from_messages(
    [
        ("system", template),
        MessagesPlaceholder(variable_name="agent_scratchpad"),
        ("human", "{input}"),
    ]
)

In [ ]:
agent = OpenAIFunctionsAgent(
    llm=ChatOpenAI(temperature=0, model="gpt-4"), prompt=prompt, tools=tools
)

In [96]:
# Defining agent
agent = create_pandas_dataframe_agent(OpenAI(temperature=0, openai_api_key = "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"), df, prompt = prompt, verbose=True)

/root/anaconda3/envs/langchain/lib/python3.11/site-packages/langchain_experimental/agents/agent_toolkits/pandas/base.py:233: UserWarning: Received additional kwargs {'prompt': ChatPromptTemplate(input_variables=['agent_scratchpad', 'input'], input_types={'agent_scratchpad': typing.List[typing.Union[langchain_core.messages.ai.AIMessage, langchain_core.messages.human.HumanMessage, langchain_core.messages.chat.ChatMessage, langchain_core.messages.system.SystemMessage, langchain_core.messages.function.FunctionMessage, langchain_core.messages.tool.ToolMessage]]}, messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], template="You are working with a pandas dataframe in Python. The name of the dataframe is `df`.\nIt is important to understand the attributes of the dataframe before working with it. This is the result of running `df.head().to_markdown()`\n\n<df>\n|    | name            | job                    | created             |   transactions |   revenue | permission   | crm_id    |\n|---:|:----------------|:-----------------------|:--------------------|---------------:|----------:|:-------------|:----------|\n|  0 | Mr. Austen Conn | Applications developer | 2002-11-15 23:03:50 |            621 |   79718.1 | TRUE         | CRM000826 |\n|  1 | Mr. Austen Conn | Applications developer | 2002-11-15 23:03:50 |            621 |   79718.1 | TRUE         | CRM000826 |\n|  2 | Mr. Austen Conn | Applications developer | 2002-11-15 23:03:50 |            621 |   79718.1 | TRUE         | CRM000826 |\n|  3 | Mr. Austen Conn | Applications developer | 2002-11-15 23:03:50 |            621 |   79718.1 | TRUE         | CRM000826 |\n|  4 | Mr. Austen Conn | Applications developer | 2002-11-15 23:03:50 |            621 |   79718.1 | TRUE         | CRM000826 |\n</df>\n\nYou are not meant to use only these rows to answer questions - they are meant as a way of telling you about the shape and schema of the dataframe.\nYou also do not have use only the information here to answer questions - you can run intermediate queries to do exporatory data analysis to give you more information as needed.\n\nYou have a tool called `person_name_search` through which you can lookup a person by name and find the records corresponding to people with similar name as the query.\nYou should only really use this if your search term contains a persons name. Otherwise, try to solve it with code.\n\nFor example:\n\n<question>How old is Jane?</question>\n<logic>Use `person_name_search` since you can use the query `Jane`</logic>\n\n<question>Who has id 320</question>\n<logic>Use `python_repl` since even though the question is about a person, you don't know their name so you can't include it.</logic>\n")), MessagesPlaceholder(variable_name='agent_scratchpad'), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['input'], template='{input}'))])} which are no longer supported.
  warnings.warn(

In [97]:
agent.run(value_per_distinct_user)

> Entering new AgentExecutor chain...
Thought: I need to find the number of unique values in the "crm_id" column and then sum the "revenue" column for each unique value.
Action: python_repl_ast
Action Input: df["crm_id"].nunique()12551255 is the number of distinct users, now I need to sum the "revenue" column for each unique value in the "crm_id" column.
Action: python_repl_ast
Action Input: df.groupby("crm_id")["revenue"].sum()crm_id
CRM000116     27812.3227812.3227812.3227812.3227812.3227812.32
CRM000272           1399.341399.341399.341399.341399.341399.34
CRM000317             13786.9413786.9413786.9413786.9413786.94
CRM000415                             967.91967.91967.91967.91
CRM000772                             24376.1324376.1324376.13
                                   ...
CRM134485                 968.58968.58968.58968.58968.58968.58
CRM134495    10347.1110347.1110347.1110347.1110347.1110347....
CRM134852    18033.5118033.5118033.5118033.5118033.5118033....
CRM134904    7730.537730.537730.537730.537730.537730.537730...
CRM134974           4731.594731.594731.594731.594731.594731.59
Name: revenue, Length: 1255, dtype: string I need to sum the values in the "revenue" column for each unique value in the "crm_id" column, but the output is not in a numerical format.
Action: python_repl_ast
Action Input: df.groupby("crm_id")["revenue"].sum().astype(float)ValueError: could not convert string to float: '27812.3227812.3227812.3227812.3227812.3227812.32' I need to remove the extra characters in the "revenue" column before converting it to a float.
Action: python_repl_ast
Action Input: df["revenue"] = df["revenue"].str.replace(r"[^0-9.]", "") The extra characters have been removed, now I can convert the "revenue" column to a float and sum the values for each unique "crm_id".
Action: python_repl_ast
Action Input: df.groupby("crm_id")["revenue"].sum().astype(float)ValueError: could not convert string to float: '27812.3227812.3227812.3227812.3227812.3227812.32' I need to check the "revenue" column again to see if there are any remaining non-numeric characters.
Action: python_repl_ast
Action Input: df["revenue"].unique()<ArrowStringArray>
[ '2748.01', '11515.29',  '7352.04',   '376.48',  '7987.04',  '2338.99',
  '2099.99',    '18.69',  '2057.98', '44514.43',
 ...
  '4264.08',  '9786.44',  '6289.37', '15022.13', '11720.95',  '3469.99',
    '698.9',   '8001.8',  '2019.54', '28149.73']
Length: 1253, dtype: string There are still some non-numeric characters in the "revenue" column, I need to remove them.
Action: python_repl_ast
Action Input: df["revenue"] = df["revenue"].str.replace(r"[^0-9.]", "") The non-numeric characters have been removed, now I can convert the "revenue" column to a float and sum the values for each unique "crm_id".
Action: python_repl_ast
Action Input: df.groupby("crm_id")["revenue"].sum().astype(float)ValueError: could not convert string to float: '27812.3227812.3227812.3227812.3227812.3227812.32' I need to check the "revenue" column again to see if there are any remaining non-numeric characters.
Action: python_repl_ast
Action Input: df["revenue"].unique()<ArrowStringArray>
[ '2748.01', '11515.29',  '7352.04',   '376.48',  '7987.04',  '2338.99',
  '2099.99',    '18.69',  '2057.98', '44514.43',
 ...
  '4264.08',  '9786.44',  '6289.37', '15022.13', '11720.95',  '3469.99',
    '698.9',   '8001.8',  '2019.54', '28149.73']
Length: 1253, dtype: string There are still some non-numeric characters in the "revenue" column, I need to remove them.
Action: python_repl_ast
Action Input: df["revenue"] = df["revenue"].str.replace(r"[^0-9.]", "") The non-numeric characters have been removed, now I can convert the "revenue" column to a float and sum the values for each unique "crm_id".
Action: python_repl_ast
Action Input: df.groupby("crm_id")["revenue"].sum().astype(float)ValueError: could not convert string to float: '27812.3227812.3227812.3227812.3227812.3227812.32' I need to check the "revenue" column again to see if there are any remaining non-numeric characters.
Action: python_repl_ast
Action Input: df["revenue"].unique()<ArrowStringArray>
[ '2748.01', '11515.29',  '7352.04',   '376.48',  '7987.04',  '2338.99',
  '2099.99',    '18.69',  '2057.98', '44514.43',
 ...
  '4264.08',  '9786.44',  '6289.37', '15022.13', '11720.95',  '3469.99',
    '698.9',   '8001.8',  '2019.54', '28149.73']
Length: 1253, dtype: string There are still some non-numeric characters in the "revenue" column, I need to remove them.
Action: python_repl_ast
Action Input: df["revenue"] = df["revenue"].str.replace(r"[^0-9.]", "") The non-numeric characters have been removed, now I can convert the "revenue" column to a float and sum the values for each unique "crm_id".
Action: python_repl_ast
Action Input: df.groupby("crm_id")["revenue"].sum().astype(float)ValueError: could not convert string to float: '27812.3227812.3227812.3227812.3227812.3227812.32' I need to check the "revenue" column again to see if there are any remaining non-numeric characters.
Action: python_repl_ast
Action Input: df["revenue"].unique()<ArrowStringArray>
[ '2748.01', '11515.29',  '7352.04',   '376.48',  '7987.04',  '2338.99',
  '2099.99',    '18.69',  '2057.98', '44514.43',
 ...
  '4264.08',  '9786.44',  '6289.37', '15022.13', '11720.95',  '3469.99',
    '698.9',   '8001.8',  '2019.54', '28149.73']
Length: 1253, dtype: string

> Finished chain.

'Agent stopped due to iteration limit or time limit.'

In [62]:
df.head()

,name,job,created,transactions,revenue,permission,crm_id
0,Mr. Austen Conn,Applications developer,2002-11-15 23:03:50,621,79718.09,TRUE,CRM000826
1,Mr. Austen Conn,Applications developer,2002-11-15 23:03:50,621,79718.09,TRUE,CRM000826
2,Mr. Austen Conn,Applications developer,2002-11-15 23:03:50,621,79718.09,TRUE,CRM000826
3,Mr. Austen Conn,Applications developer,2002-11-15 23:03:50,621,79718.09,TRUE,CRM000826
4,Mr. Austen Conn,Applications developer,2002-11-15 23:03:50,621,79718.09,TRUE,CRM000826

# Enriching CRM Data with more features

## Loading Data

In [7]:
# Load data
df_data_to_enrich = bpd.read_gbq("SELECT name, job, created, transactions, revenue, permission, crm_id, event_timestamp, event_name, device.*, geo.*, i.* FROM `annular-form-389809.merged_data.crm_ga4`, unnest(items) as i").to_pandas()

In [9]:
df = df_data_to_enrich.copy()

## Adding features

In [98]:
df.columns

Index(['name', 'job', 'created', 'transactions', 'revenue', 'permission',
       'crm_id', 'event_timestamp', 'event_name', 'category',
       'mobile_brand_name', 'mobile_model_name', 'mobile_marketing_name',
       'mobile_os_hardware_model', 'operating_system',
       'operating_system_version', 'vendor_id', 'advertising_id', 'language',
       'is_limited_ad_tracking', 'time_zone_offset_seconds', 'web_info',
       'continent', 'sub_continent', 'country', 'region', 'city', 'metro'],
      dtype='object')

#### Removing Gendered titles Titles

In [10]:
# The regex pattern looks for "Mr. ", "Mrs. ", or "Ms. " at the beginning of the string
df['name'] = df['name'].str.replace(r'^Mr\. |^Mrs\. |^Ms\. ', '', regex=True)

#### Generating unique event_id for every unique timestamp

In [11]:
import hashlib

In [12]:
# Function to generate a unique 8-digit code from the timestamp
def generate_event_id(timestamp):
    # Convert the timestamp to string to ensure hashability
    timestamp_str = str(timestamp)
    # Generate MD5 hash of the timestamp string
    hash_object = hashlib.md5(timestamp_str.encode())
    # Return the first 8 characters of the hexadecimal digest
    return hash_object.hexdigest()[:8]

# Apply the function to create the 'event_id' column
df['event_id'] = df['event_timestamp'].apply(generate_event_id)

In [176]:
df.head()

,name,job,created,transactions,revenue,permission,crm_id,event_timestamp,event_name,category,mobile_brand_name,mobile_model_name,mobile_marketing_name,mobile_os_hardware_model,operating_system,operating_system_version,vendor_id,advertising_id,language,is_limited_ad_tracking,time_zone_offset_seconds,web_info,continent,sub_continent,country,region,city,metro,event_id
0,Otho Harris,Purchasing manager,2003-11-16 19:04:58,719,2748.01,FALSE,CRM125509,1612076959662317,session_start,desktop,Google,Chrome,<Other>,<NA>,Windows,Windows 7,<NA>,<NA>,en-us,No,<NA>,"{'browser': 'Chrome', 'browser_version': '87.0'}",Americas,Northern America,United States,California,(not set),(not set),7b63f3ac
1,Dr. Tito Hettinger,"Engineer, civil (consulting)",2011-09-08 08:33:08,207,11515.29,TRUE,CRM086949,1612116213132183,first_visit,desktop,Google,Chrome,<Other>,<NA>,Web,10,<NA>,<NA>,en-gb,No,<NA>,"{'browser': 'Chrome', 'browser_version': '87.0'}",Americas,Northern America,United States,Florida,Tampa,(not set),7606cfde
2,Elder Hamill-Beatty,"Designer, jewellery",2014-03-16 03:03:51,108,7352.04,TRUE,CRM013713,1612107547772306,user_engagement,mobile,Apple,iPhone,<Other>,<NA>,iOS,iOS 14.3,<NA>,<NA>,<NA>,No,<NA>,"{'browser': 'Safari', 'browser_version': '14.0'}",Americas,Northern America,United States,Indiana,(not set),(not set),f74dcaf3
3,Rolland Hand,Network engineer,2018-11-03 14:02:31,19,376.48,TRUE,CRM018168,1612125332738442,page_view,desktop,Apple,Safari,<Other>,<NA>,Web,Intel 10.15,<NA>,<NA>,en-gb,No,<NA>,"{'browser': 'Safari', 'browser_version': '14.0'}",Americas,Northern America,United States,Louisiana,Baton Rouge,(not set),4cb1481f
4,Jase Harber,Dietitian,2011-11-09 01:09:54,77,7987.04,FALSE,CRM001445,1612131609849637,user_engagement,desktop,Google,Chrome,<Other>,<NA>,Web,10,<NA>,<NA>,<NA>,No,<NA>,"{'browser': 'Chrome', 'browser_version': '86.0'}",Asia,Eastern Asia,Japan,(not set),(not set),(not set),6c7f1ea1

#### Creating datetime features

In [13]:
# Convert 'event_timestamp' from microseconds to datetime
df['datetime'] = pd.to_datetime(df['event_timestamp'], unit='us', utc=True)

# Extract components from the datetime
df['date'] = df['datetime'].dt.date  # Date
df['year'] = df['datetime'].dt.year  # Year
df['month'] = df['datetime'].dt.month_name()  # Month as full name
df['month_number'] = df['datetime'].dt.month  # Month as number
df['week_number'] = df['datetime'].dt.isocalendar().week  # Week number
df['day_number'] = df['datetime'].dt.day  # Day of the month
df['hour'] = df['datetime'].dt.hour  # Hour of the day

In [178]:
df.head()

,name,job,created,transactions,revenue,permission,crm_id,event_timestamp,event_name,category,mobile_brand_name,mobile_model_name,mobile_marketing_name,mobile_os_hardware_model,operating_system,operating_system_version,vendor_id,advertising_id,language,is_limited_ad_tracking,time_zone_offset_seconds,web_info,continent,sub_continent,country,region,city,metro,event_id,datetime,date,year,month,month_number,week_number,day_number,hour
0,Otho Harris,Purchasing manager,2003-11-16 19:04:58,719,2748.01,FALSE,CRM125509,1612076959662317,session_start,desktop,Google,Chrome,<Other>,<NA>,Windows,Windows 7,<NA>,<NA>,en-us,No,<NA>,"{'browser': 'Chrome', 'browser_version': '87.0'}",Americas,Northern America,United States,California,(not set),(not set),7b63f3ac,2021-01-31 07:09:19.662317+00:00,2021-01-31,2021,January,1,4,31,7
1,Dr. Tito Hettinger,"Engineer, civil (consulting)",2011-09-08 08:33:08,207,11515.29,TRUE,CRM086949,1612116213132183,first_visit,desktop,Google,Chrome,<Other>,<NA>,Web,10,<NA>,<NA>,en-gb,No,<NA>,"{'browser': 'Chrome', 'browser_version': '87.0'}",Americas,Northern America,United States,Florida,Tampa,(not set),7606cfde,2021-01-31 18:03:33.132183+00:00,2021-01-31,2021,January,1,4,31,18
2,Elder Hamill-Beatty,"Designer, jewellery",2014-03-16 03:03:51,108,7352.04,TRUE,CRM013713,1612107547772306,user_engagement,mobile,Apple,iPhone,<Other>,<NA>,iOS,iOS 14.3,<NA>,<NA>,<NA>,No,<NA>,"{'browser': 'Safari', 'browser_version': '14.0'}",Americas,Northern America,United States,Indiana,(not set),(not set),f74dcaf3,2021-01-31 15:39:07.772306+00:00,2021-01-31,2021,January,1,4,31,15
3,Rolland Hand,Network engineer,2018-11-03 14:02:31,19,376.48,TRUE,CRM018168,1612125332738442,page_view,desktop,Apple,Safari,<Other>,<NA>,Web,Intel 10.15,<NA>,<NA>,en-gb,No,<NA>,"{'browser': 'Safari', 'browser_version': '14.0'}",Americas,Northern America,United States,Louisiana,Baton Rouge,(not set),4cb1481f,2021-01-31 20:35:32.738442+00:00,2021-01-31,2021,January,1,4,31,20
4,Jase Harber,Dietitian,2011-11-09 01:09:54,77,7987.04,FALSE,CRM001445,1612131609849637,user_engagement,desktop,Google,Chrome,<Other>,<NA>,Web,10,<NA>,<NA>,<NA>,No,<NA>,"{'browser': 'Chrome', 'browser_version': '86.0'}",Asia,Eastern Asia,Japan,(not set),(not set),(not set),6c7f1ea1,2021-01-31 22:20:09.849637+00:00,2021-01-31,2021,January,1,4,31,22

In [179]:
df['event_name'].unique()

<ArrowStringArray>
[      'session_start',         'first_visit',     'user_engagement',
           'page_view',      'view_promotion',         'select_item',
           'view_item',   'add_shipping_info',              'scroll',
         'add_to_cart',      'begin_checkout', 'view_search_results',
    'select_promotion',    'add_payment_info',            'purchase',
               'click']
Length: 16, dtype: string

#### Changing "permission" to "email_permission"

In [14]:
# Rename the "permission" column to "email_permissions"
df.rename(columns={'permission': 'email_permissions'}, inplace=True)

#### Adding "units_purchased" as a feature

In [181]:
# Creating function to assign quantity for 'purchase' events
def assign_quantity(event_name):
    if event_name == 'purchase':
        return np.random.randint(1, 6)  # Generate a random integer between 1 and 5
    else:
        return np.nan  # Assign NaN for non-purchase events

# Apply the function to create the 'quantity' column
df['units_purchased'] = df['event_name'].apply(assign_quantity)

#### Adding "transaction_amount" as a feature

In [182]:
# Function to calculate transaction amount
def calculate_transaction_amount(units_purchased):
    # Assuming each unit contributes an amount between 25 and 150 in a linear fashion
    # Adjust the multiplier as necessary to fit your correlation needs
    # This is a placeholder calculation and should be adjusted to your specific correlation logic
    base_amount = 25  # Minimum amount for a purchase
    if pd.isnull(units_purchased):
        return np.nan
    else:
        # Simple correlation: base_amount + a variable amount based on units_purchased
        # Ensuring the transaction amount does not exceed 150
        amount = min(base_amount + (units_purchased * (125 / 5)), 150)
        return amount

# Apply the function to create the 'transaction_amount' column
df['transaction_amount'] = df['units_purchased'].apply(calculate_transaction_amount)

In [183]:
# Filter the DataFrame for rows where 'event_name' is 'purchase'
# and select only the 'transaction_amount' and 'units_purchased' columns
purchase_transactions = df[df['event_name'] == 'purchase'][['transaction_amount', 'units_purchased']]

# Display the filtered DataFrame
print(purchase_transactions)

       transaction_amount  units_purchased
1364                125.0              4.0
2196                 50.0              1.0
2599                125.0              4.0
3612                125.0              4.0
8052                 50.0              1.0
8369                125.0              4.0
9188                 50.0              1.0
9418                100.0              3.0
11466                75.0              2.0
12331                75.0              2.0

#### Adding Age as a feature

In [16]:
import random

In [17]:
# Creating set of names from crm df
crm_names = list(set(df.name))

# Generate random ages for each name
ages = {name: random.randint(18, 70) for name in crm_names}

# Print the names and their corresponding ages
for name, age in ages.items():
    print(f"{name}: {age}")
    
# Adding ages to dataframe
df['age'] = df['name'].map(ages)

Miss Brooklynn Robel DDS: 31
Jamey Kling: 39
Latarsha Langosh: 41
Beadie Parisian: 34
Young Hamill: 41
Frida Goldner: 18
Ammon Wilderman: 55
Etter Hayes: 33
Zechariah D'Amore Jr.: 63
Hilma Dooley: 33
Benjamine Fadel: 28
Mariann Stiedemann: 51
Dr. Nery Simonis Sr.: 45
Dr. Vick Witting V: 22
Erika Wyman: 35
Brody Koch: 68
Jarrett Paucek DVM: 20
Lavonne Wilkinson: 38
Diamond Stracke: 39
Sarita Hayes: 21
Maury Considine: 25
Carey McDermott: 47
Santo Baumbach: 48
Tracey Kilback: 37
Babe Crona V: 52
Ferris Ziemann-Bechtelar: 58
Dorman Bode: 50
Coleton Fisher: 55
Taina Kiehn: 55
Marely Pouros: 66
Harlene Friesen: 47
Antonetta Kuhlman: 46
Jasmin Hackett-Orn: 61
Somer Abshire-Padberg: 67
Ima Ward: 64
Brandon Rogahn: 22
Emett Jones MD: 47
Karyn Oberbrunner: 63
Kevan Waelchi: 29
Traci O'Hara-Schuppe: 52
Mercedes Schoen: 60
Greggory Pagac DVM: 66
Marsh Gibson: 25
Eva Leannon: 56
Elvia Hauck: 44
Dominque Baumbach: 48
Dr. Sherrie Dach: 33
Merrilee O'Reilly: 42
Angelita Heathcote: 31
Acie Gerhold: 50
Philomena Christiansen-Larkin: 59
Beverly Harris: 32
Eldora Brekke: 26
Tal Powlowski: 66
Virge Zboncak: 53
Robby Prohaska DVM: 54
Yajaira Harber: 27
Joy Halvorson: 53
Dr. Kyrie Lockman DVM: 50
Renata Collins MD: 21
Sharon Ernser V: 60
Noma Harber: 56
Marin Lubowitz: 28
Quiana Stamm: 22
Miss Thora Hammes MD: 52
Serenity Johnson DDS: 63
Kelley Mohr: 48
Buell Hilpert-Weissnat: 65
Romaine Rippin: 58
Rodrigo Wunsch: 29
Tosha Botsford PhD: 42
Doctor Keeling DDS: 34
Lera O'Reilly: 21
Marcellus Fahey: 23
Flavia Dietrich: 66
Myer Rolfson: 47
Lary Friesen: 30
Hale Doyle IV: 53
Wing Nitzsche: 28
Blaine Toy-Lakin: 34
Freddy Streich-Roberts: 55
Deshawn Dibbert-Franecki: 58
Alexys Kuvalis: 28
Keon Reichel PhD: 51
Dedra Bosco-Abernathy: 43
Johnnie Goyette DDS: 37
Arvo Yost: 68
Shirley Halvorson: 25
Gilbert Cronin-Bechtelar: 23
Vertie Padberg: 58
Gunner Lakin-Muller: 47
Shatara Kerluke: 33
Stephanie Brakus-Shields: 30
Daryle Effertz-Berge: 60
Jayvon Lind: 66
Michaela Kunze-Bahringer: 68
Jerrilyn Ward: 29
Yee Kirlin: 21
Bjorn Ullrich-Kunde: 55
Etha Douglas: 38
Cherri Marquardt MD: 31
Micky Miller-Mraz: 50
Jinnie Rice MD: 18
Knox Douglas-Durgan: 25
Azzie Schinner DDS: 39
Roseanna Considine: 35
Trudi Hills: 31
Neveah Johnston: 52
Leopold Blick-Lubowitz: 70
Sannie Tillman: 59
Deontae Senger: 54
Opal Blanda: 39
Nigel Murphy MD: 51
Lennon Ortiz MD: 29
Spurgeon Balistreri: 50
Mabell Feil: 29
Jase Harber: 43
Aliyah Crooks: 53
Dr. Salomon Shanahan Jr.: 57
Lyn Padberg: 25
Dr. Vito Gleichner III: 47
Donavon Beatty: 18
Ivanna Schuster DVM: 66
Stephaine Rutherford: 66
Schuyler Vandervort: 58
Thaddeus Koss PhD: 18
Addie McCullough-Steuber: 32
Cleola Hauck DDS: 61
Edd Kohler Sr.: 22
Miss Makayla White PhD: 63
Lindsay Hessel MD: 20
Genaro Weber: 56
Alphonse Reichert: 54
Dr. Estelle Stracke: 70
Miss Lainey Strosin MD: 47
Horatio Marquardt: 29
Candy Boehm: 46
Jovita Oberbrunner: 24
Otho Harris: 63
Evander Keeling: 31
Melvin Feil: 56
Odie Vandervort DVM: 43
Faron Effertz: 45
Georganna Rogahn: 67
Hilario Torp: 32
Felton Rau: 62
Ryleigh Schinner: 62
Carmel Willms: 62
Frederick Bauch: 67
Dwaine Littel: 36
Tishie Murazik DDS: 25
Annette Sipes: 49
Miss Tessa Kuhlman: 59
Dr. Markel Schuster PhD: 18
Marius Nader-Schinner: 62
Jenifer Feeney DDS: 40
Taurean Kemmer: 22
Grayling Stracke I: 39
Hollie Simonis MD: 29
Genesis Romaguera: 59
Lennon DuBuque: 33
Dr. Shellie Daugherty: 23
Tawana Kunde-Howe: 36
Brande Mayer: 30
Etta Buckridge: 45
Eliana Hansen: 52
Dr. Abraham Johnson: 19
Jamil Huel-Barton: 53
Monnie Connelly: 33
Priscila Powlowski: 59
Harrie Hayes IV: 55
Lary Considine: 32
Elihu Mills: 47
Dr. Nigel Tremblay DDS: 47
Chancey Schaden: 48
Gustie McKenzie: 70
Shae Willms MD: 35
Ora Christiansen: 42
Cindi Wisozk: 57
Allie Howe PhD: 50
Wylie Hansen III: 53
Kenya Huels: 41
Arden Corkery: 66
Algot Goyette: 51
Bernie Schamberger: 65
Mahala McLaughlin DVM: 37
Destini Blick PhD: 61
Christine Rowe MD: 61
Tracey Schroeder: 39
Schuyler Johnson: 19
Albina Walker: 56
Cornelia Herzog: 28
Dr. Arron Schimmel: 46
Trinidad Cummerata: 51
Latisha Barrows: 28
Fount Batz: 26
Dosha Bernier MD: 53
Oda Weimann-Kuphal: 49
Carmel Thiel: 24
Hershell Keeling III: 28
Miss Buna Murazik DVM: 67
Darl Conn: 36
Wayde Barrows: 28
Vince Armstrong: 27
Exa Friesen-Mueller: 21
Rolf Mohr: 45
Dr. Jameel Feest: 55
Winfred Hagenes: 43
Dr. Dimitrios Williamson V: 52
Jamie Fisher: 60
Zetta DuBuque: 22
Jonnie Schaden-Gorczany: 58
Elmina Ratke-DuBuque: 35
Jeff Lueilwitz-Nolan: 54
Gale Pacocha: 19
Juli Bins: 60
Jaydin Cronin: 46
Elder Hamill-Beatty: 67
Vilma Zieme: 67
Trace Gerhold: 26
Pascal Cassin: 18
Anders Block: 54
Evonne Breitenberg: 62
Emmanuel Rempel II: 26
Dr. Wayland Raynor IV: 32
Max Nikolaus: 58
Kirk Stark DVM: 43
Londyn Sauer-Hahn: 50
Miss Marnie Harris MD: 40
Adalberto Gottlieb-Padberg: 25
Kamari Beer Sr.: 44
Valentine Olson: 51
Jessee Quigley: 22
Dr. Florencio Rowe: 22
Dixon Schoen: 52
Bryson Barrows: 53
Miss Dorine Metz MD: 19
Delpha VonRueden: 54
Lora Moore DDS: 58
Priscilla McCullough: 22
Doshia Hilll: 43
Starr Hartmann MD: 45
Reinaldo Spencer: 34
Dr. Steven Spinka: 45
Lavern Berge PhD: 33
Oris Hessel: 66
Reubin Daniel-Goldner: 33
Lula Koepp: 23
Agustin Klocko-Stanton: 56
Florida Runolfsson-Leffler: 51
Doreen Johnson: 21
Alvie O'Conner: 32
Christal Aufderhar: 22
Nicolas Torphy-Romaguera: 48
Cam Yost-O'Reilly: 38
Lavenia Balistreri: 69
Mary Ebert DDS: 52
Lafe Kuphal: 20
Fredy Kling: 68
Alfonzo Mraz: 44
Sylvanus Bernhard: 35
Audy Pfeffer-Romaguera: 66
Dr. Carlie Stoltenberg PhD: 35
Irven Tremblay: 25
Alvah Cronin: 40
Audra Koch-Hamill: 19
Yusuf Lubowitz: 34
Cherry Rath: 59
Perla McDermott: 59
Kirstin Hintz: 63
Raven Bechtelar: 69
Corinna Price: 64
Cassandra Nitzsche: 70
Marius Nolan: 35
Saundra Wiegand: 66
Dr. Bryan Kshlerin DDS: 61
Dallas Nolan: 47
Carson Witting: 45
Alethea Aufderhar DDS: 55
Cassandra Denesik: 52
Vela Bogan: 55
Tracy Roob: 43
Kelsi Johns: 57
Lewis Durgan-Rosenbaum: 30
Kasey Brown: 28
Che Schultz: 30
Kiara Farrell: 50
Melissa Waters: 33
Sheron Dibbert: 37
Kermit Padberg: 67
Obe Nolan III: 59
Percy Hand: 43
Link Mitchell: 29
Cathi Hane DDS: 66
Encarnacion Huel: 49
Lena O'Hara-Bogan: 25
Freddie Roberts: 21
Alcide Lehner: 35
Destin Romaguera: 64
Salomon Tillman: 39
Miss Noelle Bergnaum: 31
Emilie Schumm: 23
Wynona Johnson: 68
Miss Rosy Bartoletti DVM: 60
Elmire Lemke: 24
Chaim Durgan: 62
Annika Will DVM: 33
Dovie Ebert: 22
Jovani Cormier: 53
Dellar Feest: 50
Astrid Kuhn DVM: 19
Zollie Braun Sr.: 53
Lesta Effertz: 63
Symone Hodkiewicz PhD: 57
Kenan Renner: 70
Donny Dietrich: 56
Marchello Green: 31
Ethen VonRueden: 19
Hansford Hegmann: 61
Norman Berge: 25
Katia Jenkins MD: 32
Aria Greenfelder PhD: 27
Shannon Hauck-Steuber: 25
Farah Grant: 26
Francisquita Kassulke: 29
Deven Gottlieb: 19
Kamryn Ward: 54
Idamae Kris DDS: 18
Yehuda Hansen: 50
Tari Jast: 70
Patience Dach-Heidenreich: 62
Danae Bernhard: 53
Texanna Pfeffer: 46
Miss Lynn Abernathy DDS: 29
Hardie Kris: 54
Roxanna Stark-Reilly: 67
Naima Kessler: 33
Dagny Thompson-Kihn: 65
Laraine Turner-Heidenreich: 28
Murdock Connelly: 47
Zita Nikolaus: 70
Jordan Mills MD: 40
Berdie Bahringer: 31
Isadore Feeney: 27
Tawanda Boyer: 62
Kala Ankunding: 59
Randolf Dietrich: 44
Meta Auer: 19
Dr. Meg Ruecker: 34
Dr. Stephon Mills III: 18
Brielle White PhD: 55
Xavier Howell: 32
Shani Fisher: 48
Dr. Presley Kuhlman: 18
Migdalia Feeney: 20
Kenia O'Hara: 23
Kellen Walker: 64
Nanci Koelpin: 43
Samual Mann V: 31
Ethyle Morar: 32
Bartholomew Christiansen: 52
Alphonsus Vandervort-Wiegand: 66
Muhammad Rau PhD: 44
Dr. Lara Rice PhD: 56
Lucretia Leannon: 43
Veronica Tromp: 65
Dwight King-Rogahn: 41
Miss Katarina Wehner: 42
Alessandro Stark: 64
Chloe Will: 44
Hildegard Monahan: 26
Barron Cummerata: 42
Janessa Schultz-Sporer: 33
Clark Baumbach: 29
Kimberlie Volkman: 47
Estefania Zemlak PhD: 46
Chace Hettinger-Satterfield: 67
Otha Fay III: 62
Richmond Hagenes: 54
Mozell Dibbert: 69
Dr. Roderic Romaguera III: 19
Angelique VonRueden: 55
Miss Salina Bergnaum: 68
Dr. Regan Waelchi: 18
Little Tremblay Jr.: 46
Georgie Donnelly: 35
Texas Schinner-Boyle: 49
Norwood Padberg: 55
Orion Walter: 26
Shelvia Bosco-Doyle: 65
Israel Hodkiewicz: 54
Isam Gulgowski: 42
Red Howe: 65
Dr. Kamari Connelly IV: 36
Johnny Brown II: 51
Jimmy Doyle: 38
Bertina Kiehn MD: 19
Rosanna Hirthe: 47
Dr. Anfernee Beatty: 66
Sydney Powlowski: 43
Joe Haag: 27
Reanna Frami MD: 70
Dr. Anson Toy DDS: 61
Ezequiel Wilderman: 24
Oral Gorczany: 23
Gayle Runte: 26
Emerald Heaney DDS: 58
Evia Wunsch-O'Keefe: 58
Dr. Marsh Wisozk IV: 56
Ester Schowalter: 28
Roselyn Brekke: 36
Holland Gulgowski: 30
Roland Gleichner: 35
Jonnie Abshire: 24
Telly Shanahan V: 32

#### Adding Gender as a feature

In [19]:
# Step 1: Get unique names
unique_names = df['name'].unique()

# Step 2: Shuffle the unique names to randomize the order
np.random.shuffle(unique_names)

# Calculate the number of entries for each gender based on the proportions
num_unique = len(unique_names)
num_male = int(0.45 * num_unique)
num_female = int(0.45 * num_unique)
num_unknown = num_unique - num_male - num_female  # Ensure total adds up to the number of unique names

# Step 3: Assign genders to unique names
genders = ['male'] * num_male + ['female'] * num_female + ['unknown'] * num_unknown
gender_assignment = dict(zip(unique_names, genders))  # Create a dictionary mapping names to genders

# Step 4: Map these unique name-gender pairs back to the original dataframe
df['gender'] = df['name'].apply(lambda x: gender_assignment[x])

/tmp/ipykernel_847/2715333114.py:5: UserWarning: you are shuffling a 'ArrowStringArray' object which is not a subclass of 'Sequence'; `shuffle` is not guaranteed to behave correctly. E.g., non-numpy array/tensor objects with view semantics may contain duplicates after shuffling.
  np.random.shuffle(unique_names)

#### Adding "loyalty_program" feature

In [20]:
# Step 1: Get unique names
unique_names = df['name'].unique()

# Calculate the number of names to be assigned "loyalty_member" = 1 based on the 20% proportion
num_loyalty_members = int(0.20 * len(unique_names))

# Create an array with 0s and 1s according to the desired distribution
# Start with an array of 0s, then set the first 20% (or num_loyalty_members) to 1
loyalty_status = np.zeros(len(unique_names), dtype=int)
loyalty_status[:num_loyalty_members] = 1

# Shuffle the array to randomize the distribution of loyalty members
np.random.shuffle(loyalty_status)

# Create a dictionary mapping each unique name to its loyalty status
loyalty_assignment = dict(zip(unique_names, loyalty_status))

# Step 2: Map these unique name-loyalty status pairs back to the original dataframe
# This ensures each name has a consistent loyalty member status across the dataframe
df['loyalty_member'] = df['name'].apply(lambda x: loyalty_assignment[x])

#### Adding "Product Category" and "Product Name" features

In [185]:
# Define product categories and names
product_categories = ['Batman', 'Jurassic World', 'Marvel']
product_names = {
    'Batman': ['Batman Keychain', 'Batmobile', 'Batmobile Tumbler', 'Batwing'],
    'Jurassic World': ['Dinosaur Fossils. T. rex skull', 'Baby Dinosaur Rescue Center', 'Brachiosaurus Discovery'],
    'Marvel': ['Iron Spider-Man', 'Rocket & Baby Groot', 'Hulk Buster', 'Nano Gauntlet'],
}

# Function to assign product category and names based on units_purchased
def assign_products(row):
    if row['event_name'] == 'purchase':
        # Example logic to choose category based on some criteria, here simplified
        category = np.random.choice(product_categories)
        # Choose a random number of products to assign, e.g., 1 to 2
        num_products = np.random.randint(1, 3)
        products = np.random.choice(product_names[category], size=num_products, replace=False)
        return pd.Series([category, ', '.join(products)])
    else:
        return pd.Series([None, None])

# Apply the function to all rows and create new columns
df[['product_category', 'product_name']] = df.apply(assign_products, axis=1)

                      name                           job              created  \
0              Otho Harris            Purchasing manager  2003-11-16 19:04:58
1       Dr. Tito Hettinger  Engineer, civil (consulting)  2011-09-08 08:33:08
2      Elder Hamill-Beatty           Designer, jewellery  2014-03-16 03:03:51
3             Rolland Hand              Network engineer  2018-11-03 14:02:31
4              Jase Harber                     Dietitian  2011-11-09 01:09:54
...                    ...                           ...                  ...
13089            Tari Jast            Surveyor, quantity  2001-06-03 16:06:57
13090         Shani Fisher                 IT consultant  2001-11-27 06:18:55
13091         Marsh Gibson               Mining engineer  2014-12-16 01:38:11
13092         Etha Douglas           Pensions consultant  2008-09-17 10:55:34
13093             Red Howe          Chartered accountant  2003-02-25 11:55:50

      transactions   revenue email_permissions     crm_id   event_timestamp  \
0              719   2748.01             FALSE  CRM125509  1612076959662317
1              207  11515.29              TRUE  CRM086949  1612116213132183
2              108   7352.04              TRUE  CRM013713  1612107547772306
3               19    376.48              TRUE  CRM018168  1612125332738442
4               77   7987.04             FALSE  CRM001445  1612131609849637
...            ...       ...               ...        ...               ...
13089          370   8055.56             FALSE  CRM044778  1612075221528220
13090          160    373.44              TRUE  CRM059126  1612065424491888
13091          388  16857.19             FALSE  CRM093129  1612097704306488
13092           92  11171.68             FALSE  CRM064269  1612072777324198
13093          115  16553.99              TRUE  CRM129363  1612102504002134

            event_name category mobile_brand_name mobile_model_name  \
0        session_start  desktop            Google            Chrome
1          first_visit  desktop            Google            Chrome
2      user_engagement   mobile             Apple            iPhone
3            page_view  desktop             Apple            Safari
4      user_engagement  desktop            Google            Chrome
...                ...      ...               ...               ...
13089        page_view  desktop            Google            Chrome
13090        page_view  desktop            Google            Chrome
13091    session_start  desktop             Apple            Safari
13092  user_engagement  desktop            Google            Chrome
13093  user_engagement   mobile            Xiaomi           <Other>

      mobile_marketing_name  mobile_os_hardware_model operating_system  \
0                   <Other>                      <NA>          Windows
1                   <Other>                      <NA>              Web
2                   <Other>                      <NA>              iOS
3                   <Other>                      <NA>              Web
4                   <Other>                      <NA>              Web
...                     ...                       ...              ...
13089               <Other>                      <NA>          <Other>
13090               <Other>                      <NA>          Windows
13091               <Other>                      <NA>              Web
13092               <Other>                      <NA>              Web
13093               <Other>                      <NA>              Web

      operating_system_version  vendor_id  advertising_id language  \
0                    Windows 7       <NA>            <NA>    en-us
1                           10       <NA>            <NA>    en-gb
2                     iOS 14.3       <NA>            <NA>     <NA>
3                  Intel 10.15       <NA>            <NA>    en-gb
4                           10       <NA>            <NA>     <NA>
...                        ...        ...             ...      ...
13089                  <Other>       <NA>            <NA>     <NA>
13090               Windows 10       <NA>            <NA>    en-gb
13091              Intel 10.15       <NA>            <NA>    en-us
13092                       10       <NA>            <NA>     <NA>
13093                       10       <NA>            <NA>    en-us

      is_limited_ad_tracking  time_zone_offset_seconds  \
0                         No                      <NA>
1                         No                      <NA>
2                         No                      <NA>
3                         No                      <NA>
4                         No                      <NA>
...                      ...                       ...
13089                     No                      <NA>
13090                     No                      <NA>
13091                     No                      <NA>
13092                     No                      <NA>
13093                     No                      <NA>

                                                web_info continent  \
0       {'browser': 'Chrome', 'browser_version': '87.0'}  Americas
1       {'browser': 'Chrome', 'browser_version': '87.0'}  Americas
2       {'browser': 'Safari', 'browser_version': '14.0'}  Americas
3       {'browser': 'Safari', 'browser_version': '14.0'}  Americas
4       {'browser': 'Chrome', 'browser_version': '86.0'}      Asia
...                                                  ...       ...
13089  {'browser': 'Chrome', 'browser_version': '<Oth...  Americas
13090  {'browser': 'Chrome', 'browser_version': '<Oth...      Asia
13091   {'browser': 'Chrome', 'browser_version': '86.0'}      Asia
13092  {'browser': 'Chrome', 'browser_version': '<Oth...  Americas
13093   {'browser': 'Chrome', 'browser_version': '87.0'}  Americas

          sub_continent        country                region         city  \
0      Northern America  United States            California    (not set)
1      Northern America  United States               Florida        Tampa
2      Northern America  United States               Indiana    (not set)
3      Northern America  United States             Louisiana  Baton Rouge
4          Eastern Asia          Japan             (not set)    (not set)
...                 ...            ...                   ...          ...
13089  Northern America  United States            Washington    (not set)
13090     Southern Asia          India                Punjab     Ludhiana
13091      Western Asia   Saudi Arabia       Makkah Province       Jeddah
13092  Northern America         Canada  Prince Edward Island    (not set)
13093   Central America         Mexico       Baja California      Tijuana

           metro  event_id                         datetime        date  year  \
0      (not set)  7b63f3ac 2021-01-31 07:09:19.662317+00:00  2021-01-31  2021
1      (not set)  7606cfde 2021-01-31 18:03:33.132183+00:00  2021-01-31  2021
2      (not set)  f74dcaf3 2021-01-31 15:39:07.772306+00:00  2021-01-31  2021
3      (not set)  4cb1481f 2021-01-31 20:35:32.738442+00:00  2021-01-31  2021
4      (not set)  6c7f1ea1 2021-01-31 22:20:09.849637+00:00  2021-01-31  2021
...          ...       ...                              ...         ...   ...
13089  (not set)  1ad9d4ab 2021-01-31 06:40:21.528220+00:00  2021-01-31  2021
13090  (not set)  dac795e4 2021-01-31 03:57:04.491888+00:00  2021-01-31  2021
13091  (not set)  0c48401a 2021-01-31 12:55:04.306488+00:00  2021-01-31  2021
13092  (not set)  bc6b3a54 2021-01-31 05:59:37.324198+00:00  2021-01-31  2021
13093  (not set)  6d3491ce 2021-01-31 14:15:04.002134+00:00  2021-01-31  2021

         month  month_number  week_number  day_number  hour  units_purchased  \
0      January             1            4          31     7              NaN
1      January             1            4          31    18              NaN
2      January             1            4          31    15              NaN
3      January             1            4          31    20              NaN
4      January             1            4          31    22              NaN
...        ...           ...          ...         ...   ...              ...
13089  January             1            4          31     6              NaN
13090  January             1            4          31     3              NaN
13091  January             1            4          31    12              NaN
13092  January             1            4          31     5              NaN
13093  January             1            4          31    14              NaN

       transaction_amount  age product_category product_name
0                     NaN   33             None         None
1                     NaN   18             None         None
2                     NaN   62             None         None
3                     NaN   68             None         None
4                     NaN   48             None         None
...                   ...  ...              ...          ...
13089                 NaN   62             None         None
13090                 NaN   56             None         None
13091                 NaN   24             None         None
13092                 NaN   48             None         None
13093                 NaN   46             None         None

[13094 rows x 42 columns]

# Testing GPT agent

In [31]:
llm = OpenAI(temperature=0, openai_api_key = "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")

In [30]:
small_df = df.head(1000)

In [32]:
# Defining agent
agent = create_pandas_dataframe_agent(llm, small_df, verbose=True)

In [33]:
### Defining prompts

popular_products = "What were the most popular products that were purchased?"

In [34]:
agent.run(popular_products)

> Entering new AgentExecutor chain...
Thought: I need to find the items with the highest quantity purchased.
Action: python_repl_ast
Action Input: df.sort_values(by='quantity', ascending=False)                     name                             job  \
319        Irven Tremblay           Administrator, sports
713          Etha Douglas             Pensions consultant
945        Irven Tremblay           Administrator, sports
426          Max Nikolaus            Optician, dispensing
206       Johnny Brown II                 Physiotherapist
..                    ...                             ...
995      Ryleigh Schinner                 Quality manager
996  Serenity Johnson DDS  Chartered certified accountant
997  Serenity Johnson DDS  Chartered certified accountant
998        Deontae Senger                  Office manager
999    Oda Weimann-Kuphal            Newspaper journalist

                 created transactions   revenue email_permissions     crm_id  \
319  2012-02-02 18:29:00          154   8035.99             FALSE  CRM106501
713  2008-09-17 10:55:34           92  11171.68             FALSE  CRM064269
945  2012-02-02 18:29:00          154   8035.99             FALSE  CRM106501
426  2005-03-23 21:24:18          130  14942.42              TRUE  CRM013495
206  2013-10-19 11:40:59           53   5250.04              TRUE  CRM053343
..                   ...          ...       ...               ...        ...
995  2016-04-07 23:44:28           34    221.94              TRUE  CRM036751
996  2007-10-03 08:19:45          530  25646.49              TRUE  CRM045227
997  2007-10-03 08:19:45          530  25646.49              TRUE  CRM045227
998  2020-09-18 16:19:04           11    447.87              TRUE  CRM041745
999  2005-10-07 10:46:51          658  52438.23             FALSE  CRM096372

      event_timestamp      event_name category mobile_brand_name  \
319  1612069847783455  begin_checkout  desktop            Google
713  1612072724384624     add_to_cart  desktop            Google
945  1612069804552363     add_to_cart  desktop            Google
426  1612135482041405  begin_checkout   mobile           Samsung
206  1612073803525729       view_item  desktop            Google
..                ...             ...      ...               ...
995  1612090820247818       view_item  desktop            Google
996  1612063842459711       view_item  desktop            Google
997  1612051778045320     select_item  desktop            Google
998  1612095321494130       view_item  desktop           <Other>
999  1612133950431029       view_item   mobile             Apple

    mobile_model_name mobile_marketing_name  mobile_os_hardware_model  \
319            Chrome               <Other>                      <NA>
713            Chrome               <Other>                      <NA>
945            Chrome               <Other>                      <NA>
426           <Other>               <Other>                      <NA>
206            Chrome               <Other>                      <NA>
..                ...                   ...                       ...
995            Chrome               <Other>                      <NA>
996            Chrome               <Other>                      <NA>
997            Chrome               <Other>                      <NA>
998           <Other>               <Other>                      <NA>
999            iPhone               <Other>                      <NA>

    operating_system operating_system_version  vendor_id  advertising_id  \
319          Windows               Windows 10       <NA>            <NA>
713              Web                       10       <NA>            <NA>
945          Windows               Windows 10       <NA>            <NA>
426          Android                Android 9       <NA>            <NA>
206          Windows                Windows 7       <NA>            <NA>
..               ...                      ...        ...             ...
995              Web                       10       <NA>            <NA>
996              Web                  <Other>       <NA>            <NA>
997              Web                  <Other>       <NA>            <NA>
998          Windows               Windows 10       <NA>            <NA>
999              Web                  <Other>       <NA>            <NA>

    language is_limited_ad_tracking  time_zone_offset_seconds  \
319    en-us                     No                      <NA>
713     <NA>                     No                      <NA>
945    en-us                     No                      <NA>
426     <NA>                     No                      <NA>
206     <NA>                     No                      <NA>
..       ...                    ...                       ...
995       fr                     No                      <NA>
996    en-us                     No                      <NA>
997    en-us                     No                      <NA>
998    en-us                     No                      <NA>
999     <NA>                     No                      <NA>

                                              web_info continent  \
319  {'browser': 'Chrome', 'browser_version': '<Oth...   Oceania
713  {'browser': 'Chrome', 'browser_version': '<Oth...  Americas
945  {'browser': 'Chrome', 'browser_version': '<Oth...   Oceania
426  {'browser': 'Android Webview', 'browser_versio...  Americas
206   {'browser': 'Chrome', 'browser_version': '87.0'}    Europe
..                                                 ...       ...
995   {'browser': 'Chrome', 'browser_version': '86.0'}    Europe
996  {'browser': 'Chrome', 'browser_version': '<Oth...  Americas
997  {'browser': 'Chrome', 'browser_version': '<Oth...  Americas
998  {'browser': '<Other>', 'browser_version': '<Ot...      Asia
999    {'browser': 'Safari', 'browser_version': '604'}      Asia

        sub_continent        country                region       city  \
319       Australasia      Australia              Victoria  Melbourne
713  Northern America         Canada  Prince Edward Island  (not set)
945       Australasia      Australia              Victoria  Melbourne
426  Northern America  United States               Georgia  (not set)
206    Western Europe    Netherlands         North Holland  Amsterdam
..                ...            ...                   ...        ...
995   Southern Europe          Spain                Madrid     Madrid
996  Northern America  United States               Florida      Miami
997  Northern America  United States               Florida      Miami
998     Southern Asia          India             Rajasthan  (not set)
999     Southern Asia          India            Tamil Nadu    Chennai

         metro         item_id                          item_name item_brand  \
319  (not set)         9188234          Google Twill Cap Charcoal     Google
713  (not set)  GGOEGOAH124199                  Google Pen Citron  (not set)
945  (not set)         9188192   YouTube Twill Sandwich Cap Black    YouTube
426  (not set)         9199084      Google Land & Sea Journal Set     Google
206  (not set)    GGOEGXXX1369        Google Split Seam Tee Olive     Google
..         ...             ...                                ...        ...
995  (not set)  GGOEAOCB092899  Android Small Trace Journal Black  (not set)
996  (not set)  GGOEGAEC134910        Google Speckled Beanie Navy  (not set)
997  (not set)  GGOEADHH129499  Android Iconic Glass Bottle Green  (not set)
998  (not set)    GGOEGXXX1167   Google Youth F/C Pullover Hoodie  (not set)
999  (not set)  GGOEGBJJ099499            Google Utility Bag Grey  (not set)

           item_variant                 item_category item_category2  \
319  Single Option Only                       Apparel      (not set)
713           (not set)                          Sale      (not set)
945                                Home/Apparel/Hats/      (not set)
426  Single Option Only                                    (not set)
206                  LG  Home/Apparel/Men's / Unisex/      (not set)
..                  ...                           ...            ...
995           (not set)                    Home/Sale/      (not set)
996           (not set)            Home/Apparel/Hats/      (not set)
997           (not set)          Lifestyle/Drinkware/      (not set)
998           (not set)            Home/Apparel/Kids/      (not set)
999           (not set)        Lifestyle/Small Goods/      (not set)

    item_category3 item_category4 item_category5  price_in_usd  price  \
319      (not set)      (not set)      (not set)          <NA>   10.0
713      (not set)      (not set)      (not set)          <NA>    1.0
945      (not set)      (not set)      (not set)          <NA>   13.0
426      (not set)      (not set)      (not set)          <NA>   15.0
206      (not set)      (not set)      (not set)          <NA>   26.0
..             ...            ...            ...           ...    ...
995      (not set)      (not set)      (not set)          <NA>   13.0
996      (not set)      (not set)      (not set)          <NA>   20.0
997      (not set)      (not set)      (not set)          <NA>   24.0
998      (not set)      (not set)      (not set)          <NA>   40.0
999      (not set)      (not set)      (not set)          <NA>   10.0

     quantity  item_revenue_in_usd  item_revenue  item_refund_in_usd  \
319        10                 <NA>          <NA>                <NA>
713         3                 <NA>          <NA>                <NA>
945         3                 <NA>          <NA>                <NA>
426         2                 <NA>          <NA>                <NA>
206         1                 <NA>          <NA>                <NA>
..        ...                  ...           ...                 ...
995      <NA>                 <NA>          <NA>                <NA>
996      <NA>                 <NA>          <NA>                <NA>
997      <NA>                 <NA>          <NA>                <NA>
998      <NA>                 <NA>          <NA>                <NA>
999      <NA>                 <NA>          <NA>                <NA>

     item_refund     coupon affiliation location_id item_list_id  \
319         <NA>  (not set)   (not set)   (not set)    (not set)
713         <NA>  (not set)   (not set)   (not set)    (not set)
945         <NA>  (not set)   (not set)   (not set)    (not set)
426         <NA>  (not set)   (not set)   (not set)    (not set)
206         <NA>  (not set)   (not set)   (not set)    (not set)
..           ...        ...         ...         ...          ...
995         <NA>  (not set)   (not set)   (not set)    (not set)
996         <NA>  (not set)   (not set)   (not set)    (not set)
997         <NA>  (not set)   (not set)   (not set)    (not set)
998         <NA>  (not set)   (not set)   (not set)    (not set)
999         <NA>  (not set)   (not set)   (not set)    (not set)

    item_list_name item_list_index promotion_id            promotion_name  \
319      (not set)       (not set)    (not set)                 (not set)
713      (not set)              22    (not set)                 (not set)
945      (not set)               2    (not set)                 (not set)
426      (not set)       (not set)    (not set)                 (not set)
206      (not set)              12    (not set)  Complete Your Collection
..             ...             ...          ...                       ...
995      (not set)               6    (not set)                 (not set)
996      (not set)               4    (not set)                 (not set)
997      (not set)               8    (not set)                 (not set)
998      (not set)              12    (not set)                 (not set)
999      (not set)               6    (not set)                 (not set)

    creative_name creative_slot  event_id                         datetime  \
319     (not set)     (not set)  2554c962 2021-01-31 05:10:47.783455+00:00
713     (not set)     (not set)  564678d3 2021-01-31 05:58:44.384624+00:00
945     (not set)     (not set)  b10396fb 2021-01-31 05:10:04.552363+00:00
426     (not set)     (not set)  590d97fe 2021-01-31 23:24:42.041405+00:00
206     (not set)     (not set)  6af1098b 2021-01-31 06:16:43.525729+00:00
..            ...           ...       ...                              ...
995     (not set)     (not set)  baffc943 2021-01-31 11:00:20.247818+00:00
996     (not set)     (not set)  e311922a 2021-01-31 03:30:42.459711+00:00
997     (not set)     (not set)  753826be 2021-01-31 00:09:38.045320+00:00
998     (not set)     (not set)  e9cb5283 2021-01-31 12:15:21.494130+00:00
999     (not set)     (not set)  17c082dd 2021-01-31 22:59:10.431029+00:00

           date  year    month  month_number  week_number  day_number  hour  \
319  2021-01-31  2021  January             1            4          31     5
713  2021-01-31  2021  January             1            4          31     5
945  2021-01-31  2021  January             1            4          31     5
426  2021-01-31  2021  January             1            4          31    23
206  2021-01-31  2021  January             1            4          31     6
..          ...   ...      ...           ...          ...         ...   ...
995  2021-01-31  2021  January             1            4          31    11
996  2021-01-31  2021  January             1            4          31     3
997  2021-01-31  2021  January             1            4          31     0
998  2021-01-31  2021  January             1            4          31    12
999  2021-01-31  2021  January             1            4          31    22

     age  gender  loyalty_member
319   25    male               0
713   38  female               0
945   25    male               0
426   58  female               1
206   51  female               1
..   ...     ...             ...
995   62  female               0
996   63    male               0
997   63    male               0
998   54  female               0
999   49  female               0

[1000 rows x 66 columns]

BadRequestError: Error code: 400 - {'error': {'message': "This model's maximum context length is 4097 tokens, however you requested 6649 tokens (6393 in your prompt; 256 for the completion). Please reduce your prompt; or completion length.", 'type': 'invalid_request_error', 'param': None, 'code': None}}